;Creacion de caracteres
CarV0
	call CREATE_0VSI
	call CREATE_0VII
	call CREATE_0VSD
	call CREATE_0VID
	return
CarV1
	call CREATE_1VSI
	call CREATE_1VII
	call CREATE_1VSD
	call CREATE_1VID
	return
CarV2
	call CREATE_2VSI
	call CREATE_2VII
	call CREATE_2VSD
	call CREATE_2VID
	return
CarV3
	call CREATE_3VSI
	call CREATE_3VII
	call CREATE_3VSD
	call CREATE_3VID
	return
CarV4
	call CREATE_4VSI
	call CREATE_4VII
	call CREATE_4VSD
	call CREATE_4VID
	return
CarV5
	call CREATE_5VSI
	call CREATE_5VII
	call CREATE_5VSD
	call CREATE_5VID
	return

CarT0
	call CREATE_0TSI
	call CREATE_0TII
	call CREATE_0TSD
	call CREATE_0TID
	return
CarT16
	call CREATE_16TSI
	call CREATE_16TII
	call CREATE_16TSD
	call CREATE_16TID
	return
CarT24
	call CREATE_24TSI
	call CREATE_24TII
	call CREATE_24TSD
	call CREATE_24TID
	return
CarT32
	call CREATE_32TSI
	call CREATE_32TII
	call CREATE_32TSD
	call CREATE_32TID
	return
CarT40
	call CREATE_40TSI
	call CREATE_40TII
	call CREATE_40TSD
	call CREATE_40TID
	return
CarT56
	call CREATE_56TSI
	call CREATE_56TII
	call CREATE_56TSD
	call CREATE_56TID
	return